<?php
/*
 * Hotline Tracker Footer
 *
 * This file closes all the main layout tags.
 */
?>
            </div> <!-- End #content -->
        </div> <!-- End #main-content -->
        
        <div class="footer">
            Page generated by PHP/MySQL.
        </div>

    </div> <!-- End #page-container -->
    
</body>
</html>
